### ISSUE TITLE
Bash code chunk doesn't run individually

### ISSUE THREAD

**Issue by sarah-gao** [ZimmermanLab/gao-thesis#1]
@naupaka I added a comment in this commit bde0360 to show where that's happening. If I change my RStudio preferences to show outputs inline, then it does work and even the "run current chunk" etc icons reappear on the right. Seems like other folks have had the same issue https://github.com/rstudio/rstudio/issues/8786

I haven't tried running the whole Rmd with that chunk added quite yet as the CO2 stuff can be kind of scary to run given how long it takes and I would probably want to reroute the outputs to a new folder so as to not overwrite the existing cleaned data files.

**Comment by naupaka** [comment]
Does any bash code work in that chunk? If you comment out your line and instead just do 

```bash
pwd
ls
```

does it work?

Seems to knit for me, although no chunk buttons:

<img width="823" alt="CleanShot 2023-04-25 at 17 15 39@2x" src="https://user-images.githubusercontent.com/1428071/234434968-3c9d5dc9-ad63-40b4-a51c-ab7857e918c4.png">

<img width="872" alt="CleanShot 2023-04-25 at 17 16 11@2x" src="https://user-images.githubusercontent.com/1428071/234434986-6337f502-c832-4fd1-9eca-20a12e74bb6d.png">

**Comment by sarah-gao** [comment]
So you're able to run that code chunk on its own? Or it only worked when you knit the whole Rmd?

Even with that I get an "Error: object 'pwd' not found". Other bash code doesn't seem to work either:
<img width="576" alt="image" src="https://user-images.githubusercontent.com/4561390/234435502-b4cea594-c282-4832-a407-35a3b05eb190.png">

It's only when I turn on the inline output preference that I don't get an error:
<img width="957" alt="image" src="https://user-images.githubusercontent.com/4561390/234435660-f62c2203-e78e-48c3-8f27-124f875e36df.png">

**Comment by naupaka** [comment]
My guess is that it's because if you don't have output inline, it would have to open a terminal tab and run it, which might not be in the right context, so it just sends it to the R interpreter instead. If this is true, that would explain why it knits fine and why it works if output inline is set to true. I would expect the same for other outputs like python.

**Comment by naupaka** [comment]
It's executing that bash code at the R prompt.

**Comment by naupaka** [comment]
I guess just put output inline as a workaround? Does knitting work? You could try in a small test document instead of the full workflow.

**Comment by sarah-gao** [comment]
I guess if it works for you, and presumably will for me when knit, I'm not too worried about it. I am running an outdated version of RStudio because my laptop is too old to be supported by anyone these days lol 😢 so I just wanted to make sure it wasn't a universal issue.

**Comment by naupaka** [comment]
Eventually we will probably add a dockerfile and an renv lockfileto standardize the versions of things once it's mostly done. That will make sure it's portable across different machines.

I think for now the show output inline is probably a reasonable concession (even though I don't like all that output in the document, myself, I don't suppose it's hurting anything to have it there).

**Comment by naupaka** [comment]
Closing since it looks like there's a workable solution.
